/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as ProctorRouteImport } from './routes/proctor'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ExamCheckRouteImport } from './routes/exam.check'
import { Route as ExamLiveRouteImport } from './routes/exam.live'
import { Route as ExamRulesRouteImport } from './routes/exam.rules'
import { Route as FacultyLoginRouteImport } from './routes/faculty.login'
import { Route as StudentLoginRouteImport } from './routes/student.login'
import { Route as ApiPublicSebStatusRouteImport } from './routes/api/public/seb-status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const ProctorRoute = ProctorRouteImport.update({
  id: '/proctor',
  path: '/proctor',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ExamCheckRoute = ExamCheckRouteImport.update({
  id: '/exam/check',
  path: '/exam/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamLiveRoute = ExamLiveRouteImport.update({
  id: '/exam/live',
  path: '/exam/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRulesRoute = ExamRulesRouteImport.update({
  id: '/exam/rules',
  path: '/exam/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyLoginRoute = FacultyLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => FacultyRoute,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student/login',
  path: '/student/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSebStatusRoute = ApiPublicSebStatusRouteImport.update({
  id: '/api/public/seb-status',
  path: '/api/public/seb-status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/faculty': typeof FacultyRouteWithChildren
  '/proctor': typeof ProctorRoute
  '/register': typeof RegisterRoute
  '/results': typeof ResultsRoute
  '/admin/login': typeof AdminLoginRoute
  '/exam/check': typeof ExamCheckRoute
  '/exam/live': typeof ExamLiveRoute
  '/exam/rules': typeof ExamRulesRoute
  '/faculty/login': typeof FacultyLoginRoute
  '/student/login': typeof StudentLoginRoute
  '/api/public/seb-status': typeof ApiPublicSebStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/faculty': typeof FacultyRouteWithChildren
  '/proctor': typeof ProctorRoute
  '/register': typeof RegisterRoute
  '/results': typeof ResultsRoute
  '/admin/login': typeof AdminLoginRoute
  '/exam/check': typeof ExamCheckRoute
  '/exam/live': typeof ExamLiveRoute
  '/exam/rules': typeof ExamRulesRoute
  '/faculty/login': typeof FacultyLoginRoute
  '/student/login': typeof StudentLoginRoute
  '/api/public/seb-status': typeof ApiPublicSebStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/faculty': typeof FacultyRouteWithChildren
  '/proctor': typeof ProctorRoute
  '/register': typeof RegisterRoute
  '/results': typeof ResultsRoute
  '/admin/login': typeof AdminLoginRoute
  '/exam/check': typeof ExamCheckRoute
  '/exam/live': typeof ExamLiveRoute
  '/exam/rules': typeof ExamRulesRoute
  '/faculty/login': typeof FacultyLoginRoute
  '/student/login': typeof StudentLoginRoute
  '/api/public/seb-status': typeof ApiPublicSebStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/faculty'
    | '/proctor'
    | '/register'
    | '/results'
    | '/admin/login'
    | '/exam/check'
    | '/exam/live'
    | '/exam/rules'
    | '/faculty/login'
    | '/student/login'
    | '/api/public/seb-status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/faculty'
    | '/proctor'
    | '/register'
    | '/results'
    | '/admin/login'
    | '/exam/check'
    | '/exam/live'
    | '/exam/rules'
    | '/faculty/login'
    | '/student/login'
    | '/api/public/seb-status'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/faculty'
    | '/proctor'
    | '/register'
    | '/results'
    | '/admin/login'
    | '/exam/check'
    | '/exam/live'
    | '/exam/rules'
    | '/faculty/login'
    | '/student/login'
    | '/api/public/seb-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FacultyRoute: typeof FacultyRouteWithChildren
  ProctorRoute: typeof ProctorRoute
  RegisterRoute: typeof RegisterRoute
  ResultsRoute: typeof ResultsRoute
  ExamCheckRoute: typeof ExamCheckRoute
  ExamLiveRoute: typeof ExamLiveRoute
  ExamRulesRoute: typeof ExamRulesRoute
  StudentLoginRoute: typeof StudentLoginRoute
  ApiPublicSebStatusRoute: typeof ApiPublicSebStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proctor': {
      id: '/proctor'
      path: '/proctor'
      fullPath: '/proctor'
      preLoaderRoute: typeof ProctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/exam/check': {
      id: '/exam/check'
      path: '/exam/check'
      fullPath: '/exam/check'
      preLoaderRoute: typeof ExamCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/live': {
      id: '/exam/live'
      path: '/exam/live'
      fullPath: '/exam/live'
      preLoaderRoute: typeof ExamLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/rules': {
      id: '/exam/rules'
      path: '/exam/rules'
      fullPath: '/exam/rules'
      preLoaderRoute: typeof ExamRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/login': {
      id: '/faculty/login'
      path: '/login'
      fullPath: '/faculty/login'
      preLoaderRoute: typeof FacultyLoginRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/student/login': {
      id: '/student/login'
      path: '/student/login'
      fullPath: '/student/login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/seb-status': {
      id: '/api/public/seb-status'
      path: '/api/public/seb-status'
      fullPath: '/api/public/seb-status'
      preLoaderRoute: typeof ApiPublicSebStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FacultyRouteChildren {
  FacultyLoginRoute: typeof FacultyLoginRoute
}

const FacultyRouteChildren: FacultyRouteChildren = {
  FacultyLoginRoute: FacultyLoginRoute,
}

const FacultyRouteWithChildren =
  FacultyRoute._addFileChildren(FacultyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FacultyRoute: FacultyRouteWithChildren,
  ProctorRoute: ProctorRoute,
  RegisterRoute: RegisterRoute,
  ResultsRoute: ResultsRoute,
  ExamCheckRoute: ExamCheckRoute,
  ExamLiveRoute: ExamLiveRoute,
  ExamRulesRoute: ExamRulesRoute,
  StudentLoginRoute: StudentLoginRoute,
  ApiPublicSebStatusRoute: ApiPublicSebStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
